export const mockReportData = {
  defaultDomain: "adrforums.net",

  score: {
    malicious: 0,
    total: 94,
    label: "Community Score",
  },

  info: {
    creationDate: "2 months ago",
    lastAnalysisDate: "1 hour ago",
  },

  cleanVendors: [
    "Abusix",
    "ADMINUSLabs",
    "AlienVault",
    "BitDefender",
    "Certego",
    "CMC Threat Intelligence",
    "Criminal IP",
    "Cyble",
    "desenmascara.me",
    "Dr.Web",
    "Emsisoft",
    "ESTsecurity",
    "G-Data",
    "GreenSnow",
    "IPsum",
    "LevelBlue",
    "Malwared",
    "OpenPhish",
    "Phishtank",
    "Quick Heal",
    "Scantitan",
    "Seclookup",
    "Sophos",
    "Sucuri SiteCheck",
    "URLhaus",
    "VirilBack",
    "Webroot",
    "ZeroCERT",
  ],

  cleanVendorsRight: [
    "Acronis",
    "AILabs (MONITORAPP)",
    "Antiy-AVL",
    "Blueliv",
    "CINS Army",
    "CRDF",
    "CTX.AI",
    "CyRadar",
    "DNS8",
    "EmergingThreats",
    "ESET",
    "Fortinet",
    "Google Safebrowsing",
    "Heimdal Security",
    "Juniper Networks",
    "Lionic",
    "MalwarePatrol",
    "Phishing Database",
    "PREBYTES",
    "Quttera",
    "SCUMWARE.org",
    "SOCRadar",
    "StopForumSpam",
    "ThreatHive",
    "Viettel Threat Intelligence",
    "VX Vault",
    "Yandex Safebrowsing",
    "0xSI_f3Rd",
  ],

  unratedVendors: [
    "alphaMountain.ai",
    "ArcSight Threat Intelligence",
    "Azur",
    "Bkav",
    "Chong Lua Dao",
    "CSIS Security Group",
    "Ermes",
    "GCP Abuse Intelligence",
    "Gridinsoft",
    "Hunt.io Intelligence",
    "Lumu",
    "Mimecast",
    "PhishFort",
    "PrecisionSec",
    "Sansec eComscan",
    "Snort IP sample list",
    "VIPRE",
    "ZeroFox",
  ],

  unratedVendorsRight: [
    "AlphaSOC",
    "AutoShun",
    "Bifore.AI PreCrime",
    "ChainPatrol",
    "Cluster25",
    "Cyan",
    "Forcepoint ThreatSeeker",
    "GreyNoise",
    "Guardpot",
    "Kaspersky",
    "MalwareURL",
    "Netcraft",
    "PhishLabs",
    "SafeToOpen",
    "SecureBrain",
    "URLQuery",
    "Xcitium Verdict Cloud",
    "",
  ],

  footerLinks: {
    ourProduct: ["Contact Us", "Get Support", "How it Works", "ToS | Privacy Notice", "Blog | Releases"],
    community: ["Join Community", "Vote and Comment", "Contributors", "Top Users", "Community Buzz"],
    tools: ["API Scripts", "YARA", "Desktop Apps", "Browser Extensions", "Mobile App"],
    premiumServices: ["Get a demo", "Intelligence", "Reports", "Hunting", "Graph", "API v3 | v2"],
    documentation: ["Searching", "Reports", "API v3 | v2", "Graph", "Use Cases"],
  },
};
